"""init_table_hotel

Revision ID: d1a8f1d7aa81
Revises: 
Create Date: 2020-05-29 09:15:10.990800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1a8f1d7aa81'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotels',
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=False),
    sa.Column('city_or_province', sa.VARCHAR(length=255), nullable=False),
    sa.Column('address', sa.VARCHAR(length=255), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=255), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('room_types', sa.VARCHAR(length=255), nullable=False),
    sa.Column('utilities', sa.VARCHAR(length=255), nullable=False),
    sa.Column('checkin', sa.TIME(), nullable=False),
    sa.Column('checkout', sa.TIME(), nullable=False),
    sa.Column('image', sa.VARCHAR(length=255), nullable=False),
    sa.Column('longitude', sa.FLOAT(), nullable=False),
    sa.Column('latitude', sa.FLOAT(), nullable=False),
    sa.Column('price_standard', sa.INTEGER(), nullable=True),
    sa.Column('available_room_standard', sa.INTEGER(), nullable=True),
    sa.Column('tax_standard', sa.FLOAT(), nullable=True),
    sa.Column('image_standard', sa.VARCHAR(length=255), nullable=True),
    sa.Column('price_deluxe', sa.INTEGER(), nullable=True),
    sa.Column('available_room_deluxe', sa.INTEGER(), nullable=True),
    sa.Column('tax_deluxe', sa.FLOAT(), nullable=True),
    sa.Column('image_deluxe', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hotels')
    # ### end Alembic commands ###
